apiVersion: skaffold/v2beta26
kind: Config

build:
  local:
    push: false   # Important: do NOT push to Docker Hub
  artifacts:
    - image: zeroop/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: src  # matches WORKDIR/src in Dockerfile
    - image: zeroop/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: src  # matches WORKDIR/src in Dockerfile
    - image: zeroop/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*   # your Deployment/Service manifests